version: '3.8'

services:
  reservey-db:
    image: postgres:16-alpine
    container_name: reservey-db
    environment:
      POSTGRES_DB: reservey
      POSTGRES_USER: reservey_user
      POSTGRES_PASSWORD: Reservey@2026!Secure
    ports:
      - "5432:5432"
    volumes:
      - reservey_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  reservey_db_data:
    driver: local